# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sale.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 3, "", "sale.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nsale.proto\x12\x04sale"\x94\x01\n\x0bSalePayload\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\x11\n\tsub_brand\x18\x03 \x01(\t\x12\x15\n\rcampaign_name\x18\x04 \x01(\t\x12\x13\n\x0bsale_amount\x18\x05 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x12\x11\n\tmmm_model\x18\x07 \x01(\t"\xa7\x02\n\x0cSaleEnvelope\x12\x12\n\nevent_uuid\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_ts\x18\x02 \x01(\x03\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x18\n\x0boccurred_ts\x18\x04 \x01(\x03H\x00\x88\x01\x01\x12\x14\n\x07\x63hannel\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0erequest_origin\x18\x06 \x01(\tH\x02\x88\x01\x01\x12"\n\x07payload\x18\x07 \x01(\x0b\x32\x11.sale.SalePayload\x12,\n\x0cprev_payload\x18\x08 \x01(\x0b\x32\x11.sale.SalePayloadH\x03\x88\x01\x01\x42\x0e\n\x0c_occurred_tsB\n\n\x08_channelB\x11\n\x0f_request_originB\x0f\n\r_prev_payloadb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sale_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SALEPAYLOAD"]._serialized_start = 21
    _globals["_SALEPAYLOAD"]._serialized_end = 169
    _globals["_SALEENVELOPE"]._serialized_start = 172
    _globals["_SALEENVELOPE"]._serialized_end = 467
# @@protoc_insertion_point(module_scope)
