apiVersion: v1
kind: Service
metadata:
  name: fkl-streamer-app-service
spec:
  selector:
    app: fkl-streamer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  # Use LoadBalancer if exposing externally